### ISSUE TITLE
inicializacija peteric

### ISSUE THREAD

**Issue by GalKuhar** [GalKuhar/Gomoku#2]
v razredu `igra` `int[] peterica_x = new int[5]` mora biti `int[] peterica_x = new int[PET]`

**Comment by andrejbauer** [comment]
Kodo se piše med backquote (nazaj apostrofe). Torej `Igri int[] peterica_x = new int[5]`.

Pa bolje bi bilo, če bi povedal, v kateri datoteki se to najde. Kje naj to iščem?
