### ISSUE TITLE
preverjanje konec igre

### ISSUE THREAD

**Issue by GalKuhar** [GalKuhar/Gomoku#5]
Gomoku se lahko konča z več kot eno polno peterico. Malo popravi kodo v igri.

**Comment by andrejbauer** [comment]
A pa je nujno, da poiščeta vse peterice? A ni dovolj, da se uporabniku pokaže ena? Ali je še kak drug razlog, da je treba vedeti za vse peterice?

**Comment by GalKuhar** [comment]
Če bomo meli enkrat save file morebiti dobro, če na začetku preveri ali sploh veljavno.
Bova napisala dve funkciji - eno za na začetku preveriti, drugo pa za sproti.
Ta sproti dovolj da najde eno.

**Comment by andrejbauer** [comment]
Kaj naj bi počel "save file", shranjeval pozicijo? Ne s tem časa izgubljat, raje investirajta v to, da vaju bo računalnik premagal.
