### ISSUE TITLE
Preveč stvari public

### ISSUE THREAD

**Issue by GalKuhar** [GalKuhar/Gomoku#8]
Mislim da sem, ko sem pisal prvo verzijo funkcije preveč stvari nastavil na public. Lahko vprašava na vajah.

**Comment by andrejbauer** [comment]
Recept je naslednji: vsako metodo v razredu `X` narediš `private`, če pa se izkaže, da to povzroča težave, ker hoče razred `Y` dostopati do metode, potem greš razmišljat, katera od dveh možnosti je pravilna:

1.  Metoda mora ostati `private`, tisto kar delaš v `Y` pa preseliš v `X`.
2. Metoda mora biti `public`.

**Comment by GalKuhar** [comment]
Vprašanje: če nekaj nastavim na private, in mi samo test class javlja napake, morem to pustiti na public, ali se to da kako drugače - lahko test kako dostopa do private?

**Comment by andrejbauer** [comment]
Da se [pohekirat](http://www.onjava.com/pub/a/onjava/2003/11/12/reflection.html), da lahko dostopaš do private atributov, ampak to odsvetujem. Bolje je, da o JUnit testu razmišljaš nekoliko drugače: testi naj preizkusijo kako se razred obnaša *navzven*. Če ti testi uspejo, potem je načeloma vseeno, kaj razred počne privatno (predstavljaj si, da bi razred malo drugače implementiral, ali bi vse unit teste še enkrat pisal?)
