### ISSUE TITLE
Bug pri inicializaciji peteric

### ISSUE THREAD

**Issue by GalKuhar** [GalKuhar/Gomoku#9]
Vsakič ko poženemo novo igro, se v tabelo peteric dodajo vse peterice. To odkrili preko `testTabelePeterice`, ki zaradi tega trenutno ne deluje.

**Comment by GalKuhar** [comment]
@petrapodlogar malo poglej če najdeš rešitev, drugače vprašava na vajah.

**Comment by andrejbauer** [comment]
Aja, meni koda v `Igra.java` za inicializacijo izgleda ok. Kaj pa se zgodi, če dopišeš pred zanke, ki naračunajo peterice še to, da se seznam peteric nastavi na praznega?  [Tukaj nekje](https://github.com/GalKuhar/Gomoku/blob/master/Gomoku/src/logika/Igra.java#L21) dodaš še

```java
peterice = new LinkedList<Peterica>();
```

A potem dela?

**Comment by GalKuhar** [comment]
Če napišem kot `List<Peterica> peterice = new LinkedList<Peterica>();` potem vsi testi razen osnovna igra failajo.
Ne pusti mi pa direkt nastaviti peterice, saj so te final.

**Comment by GalKuhar** [comment]
Če odstranim final iz peteric in jih nastavim z `peterice = new LinkedList<Peterica>();`, potem vsi testi delujejo.

**Comment by andrejbauer** [comment]
Uh, narobe sem vas naučil inicizalizaicjo. Pred tisti blok je treba napisati še `static`, torej: 

```java
static {	// Inicializiramo Peterice
		
		// Naredimo tabelo peteric
		// smer navzdol desno +
		int[][] smer = {{1,0}, {0,1}, {1,1}, {1,-1}};
                // IN TAKO NAPREJ
```

**Comment by GalKuhar** [comment]
Aha, zdej dela tudi če so peterice final.
